In [4]:
import pandas as pd
import os
import numpy as np
import matplotlib.ticker as mtick
from IPython.display import display, Markdown

#import arcgis libraries
from arcgis.gis import *
gis = GIS()

In [12]:
working_directory = os.getcwd()
#data_folder =  os.path.join(working_directory, "data")
results_folder = os.path.join(working_directory, "results")

tract_filename = os.path.join(working_directory, r"tl_2018_49_tract\tl_2018_49_tract.shp")

tazcentroids_filename = working_directory + r"\TAZ\TAZCentroids.shp"

tazcentroids_zipcode_sj = working_directory + r"\Results\Shapefile\TAZCentroids_Tract.shp"

In [11]:
sdf_tract = pd.DataFrame.spatial.from_featureclass(tract_filename)

sdf_tract.head()

,FID,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,SHAPE
0,0,49,049,001001,49049001001,10.01,Census Tract 10.01,G5020,S,1693893.0,0.0,+40.2934782,-111.6812127,"{""rings"": [[[-111.695025, 40.297128], [-111.69..."
1,1,49,049,001002,49049001002,10.02,Census Tract 10.02,G5020,S,1508099.0,0.0,+40.2861635,-111.6792437,"{""rings"": [[[-111.691801, 40.289775], [-111.68..."
2,2,49,049,001103,49049001103,11.03,Census Tract 11.03,G5020,S,2084741.0,0.0,+40.2784944,-111.7079769,"{""rings"": [[[-111.724595, 40.282503], [-111.72..."
3,3,49,049,001201,49049001201,12.01,Census Tract 12.01,G5020,S,2463956.0,0.0,+40.2670294,-111.7036321,"{""rings"": [[[-111.718699, 40.27531], [-111.718..."
4,4,49,049,001202,49049001202,12.02,Census Tract 12.02,G5020,S,1697208.0,0.0,+40.2662170,-111.6886343,"{""rings"": [[[-111.695103, 40.273556], [-111.69..."

In [14]:
#verify that shape exists and sdf was created correctly and get spatial reference
print(sdf_tract.iloc[0].SHAPE)

{'rings': [[[-111.695025, 40.297128], [-111.693263, 40.297140999999996], [-111.692007, 40.297151], [-111.69186, 40.297149], [-111.689658, 40.297118999999995], [-111.68838, 40.297101], [-111.688128, 40.297095999999996], [-111.687239, 40.297081], [-111.685969, 40.297059999999995], [-111.684589, 40.297039999999996], [-111.683482, 40.297024], [-111.68286499999999, 40.297014999999995], [-111.682499, 40.297008999999996], [-111.681632, 40.296997], [-111.68086, 40.296985], [-111.68009599999999, 40.296974], [-111.67965699999999, 40.296966999999995], [-111.679595, 40.296966], [-111.679296, 40.296962], [-111.678873, 40.296956], [-111.676455, 40.296921], [-111.674827, 40.296892], [-111.673875, 40.296878], [-111.672982, 40.296861], [-111.67259, 40.296866], [-111.67174, 40.296895], [-111.669978, 40.296951], [-111.668862, 40.296988999999996], [-111.667273, 40.297042999999995], [-111.667587, 40.296633], [-111.667777, 40.296425], [-111.667699, 40.296375999999995], [-111.667718, 40.296310999999996], [-111.667832, 40.296309], [-111.667917, 40.296127], [-111.667956, 40.296045], [-111.668068, 40.295477999999996], [-111.668102, 40.295401], [-111.66821, 40.295151], [-111.668522, 40.294846], [-111.668834, 40.294584], [-111.668918, 40.294332999999995], [-111.668917, 40.293679999999995], [-111.669101, 40.293492], [-111.669116, 40.293478], [-111.66940000000001, 40.293244], [-111.669464, 40.293223999999995], [-111.669542, 40.293192999999995], [-111.669717, 40.293122], [-111.669741, 40.293113], [-111.669855, 40.29309], [-111.669843, 40.292964999999995], [-111.669433, 40.293119], [-111.6696, 40.292390999999995], [-111.669351, 40.292381], [-111.669247, 40.292293], [-111.66927, 40.291778], [-111.669286, 40.291531], [-111.66931, 40.291456], [-111.669342, 40.291382], [-111.669601, 40.290921999999995], [-111.669657, 40.290803], [-111.669714, 40.290661], [-111.669753, 40.290545], [-111.66977, 40.290431], [-111.669764, 40.290409], [-111.669729, 40.290276], [-111.669725, 40.290189999999996], [-111.669723, 40.29007], [-111.66972, 40.289944999999996], [-111.669736, 40.289839], [-111.669768, 40.289764999999996], [-111.669974, 40.28975], [-111.67019, 40.289719], [-111.671352, 40.289697], [-111.67258, 40.289666], [-111.673718, 40.289635], [-111.675038, 40.289598999999995], [-111.676272, 40.289567999999996], [-111.678692, 40.2896], [-111.679878, 40.289614], [-111.681988, 40.289643], [-111.682807, 40.289654999999996], [-111.68422, 40.289674999999995], [-111.685744, 40.289694999999995], [-111.686116, 40.289699], [-111.686992, 40.289708999999995], [-111.688177, 40.289727], [-111.689502, 40.289744999999996], [-111.691801, 40.289775], [-111.69339, 40.293451999999995], [-111.694147, 40.295168], [-111.694253, 40.295409], [-111.695025, 40.297128]]], 'spatialReference': {'wkid': 4269, 'latestWkid': 4269}}

In [18]:
#change projection to 26912 to match TAZ Centroids
sdf_tract.spatial.project(26912)

True

In [19]:
#verify that shape exists and sdf was created correctly and get spatial reference
print(sdf_tract.iloc[0].SHAPE)

{'rings': [[[440930.5773151074, 4460968.086739703], [441080.3402932315, 4460968.356273382], [441187.0958829643, 4460968.631612168], [441199.5876160399, 4460968.312032494], [441386.70872411336, 4460963.522810763], [441495.3099098532, 4460960.680041071], [441516.7229835794, 4460959.958655741], [441592.2658453161, 4460957.707164751], [441700.1846415312, 4460954.539634956], [441817.4532234628, 4460951.412396772], [441911.5231039063, 4460948.909954835], [441963.95405058796, 4460947.506574141], [441995.0551548198, 4460946.600872853], [442068.7309926295, 4460944.701562675], [442134.3328284647, 4460942.86502527], [442199.2556198625, 4460941.145276869], [442236.56016192446, 4460940.081947667], [442241.8286758242, 4460939.930524311], [442267.2372111595, 4460939.291628919], [442303.18277999153, 4460938.3500548275], [442508.6583855081, 4460932.893085382], [442646.9972769179, 4460928.618879648], [442727.89578705747, 4460926.44900084], [442803.77739567874, 4460923.985092372], [442837.0976415311, 4460924.287053725], [442909.363439557, 4460926.957828407], [443059.16252991767, 4460932.0396086145], [443154.0429437509, 4460935.540759915], [443289.1367317593, 4460940.516147454], [443262.1070326853, 4460895.208370295], [443245.7848696309, 4460872.242667886], [443252.3731279184, 4460866.753837912], [443250.7039281223, 4460859.5511934925], [443241.0133315713, 4460859.402234493], [443233.63682299614, 4460839.255214923], [443230.2535548123, 4460830.178439455], [443220.25996425154, 4460767.314831416], [443217.3057937101, 4460758.789843347], [443207.91738414956, 4460731.109787019], [443181.1444058389, 4460697.455720103], [443154.4072242031, 4460668.574624491], [443147.0574727928, 4460640.7682474675], [443146.59519291174, 4460568.286482582], [443130.79872101074, 4460547.537121941], [443129.51207304874, 4460545.992791254], [443105.1774945781, 4460520.201815032], [443099.7210776941, 4460518.022976076], [443093.0655078301, 4460514.632165539], [443078.1319019078, 4460506.863795528], [443076.0844806387, 4460505.88024209], [443066.37579738913, 4460503.400563757], [443067.2908283394, 4460489.518213258], [443102.26783905504, 4460506.348369427], [443087.46301108634, 4460425.649744696], [443108.61849695334, 4460424.379846575], [443117.3842412687, 4460414.545322918], [443114.99751606095, 4460357.396589318], [443113.4304638864, 4460329.990583312], [443111.32765634754, 4460321.681212847], [443108.54570909194, 4460313.487977241], [443086.14566213026, 4460262.595671084], [443081.28597616806, 4460249.422995381], [443076.3219784262, 4460233.698032898], [443072.9097374393, 4460220.847431671], [443071.36911797273, 4460208.20468985], [443071.86064557015, 4460205.758899209], [443074.723981115, 4460190.973801766], [443074.99181641743, 4460181.4254848035], [443075.06112895306, 4460168.104553163], [443075.2112457425, 4460154.227994036], [443073.7623304312, 4460142.472586831], [443070.9802808884, 4460134.279366261], [443053.45794600854, 4460132.74679588], [443035.0721814987, 4460129.444742889], [442936.2850477457, 4460127.750567141], [442831.8803364296, 4460125.101297374], [442735.12542954204, 4460122.395299903], [442622.89638821816, 4460119.253407512], [442517.981375743, 4460116.612372583], [442312.3109317807, 4460121.7371560065], [442211.5140481264, 4460124.064006691], [442032.1909727936, 4460128.661301916], [441962.587097541, 4460130.529438282], [441842.5007412065, 4460133.675936032], [441712.97957250534, 4460136.897368081], [441681.3634216412, 4460137.586153075], [441606.9129985919, 4460139.273105099], [441506.2048410877, 4460142.052729902], [441393.59689484315, 4460144.926300375], [441198.21054670255, 4460149.779498721], [441066.34168789786, 4460558.971919474], [441003.4934929677, 4460749.9470147565], [440994.6939708334, 4460776.767948467], [440930.5773151074, 4460968.086739703]]], 'spatialReference': {'wkid': 26912, 'latestWkid': 26912}}

In [13]:
sdf_tazcentroids = pd.DataFrame.spatial.from_featureclass(tazcentroids_filename)

sdf_tazcentroids.head()

,FID,TAZID,SORT,CO_TAZID,SUBAREAID,EXTERNAL,ACRES,DEVACRES,X,Y,...,DLRG_NAME,DISTMED,DMED_NAME,DISTSML,DSML_NAME,AIRSAGE,WF_AIRSAGE,SLC,NAAPM25,SHAPE
0,0,460,1,110460,1,0,322.29,322.29,409807.97148,4.551224e+06,...,North Davis,11,Clinton-W.Pt-Clearfield,98,Clinton-W.Pt-Clearfield,1106,13,2,NonAttnmnt|11|WFRC,"{""x"": 409807.9715, ""y"": 4551223.84, ""spatialRe..."
1,1,461,2,110461,1,0,316.91,316.91,409818.05584,4.552025e+06,...,North Davis,11,Clinton-W.Pt-Clearfield,98,Clinton-W.Pt-Clearfield,1106,13,2,NonAttnmnt|11|WFRC,"{""x"": 409818.0558000002, ""y"": 4552025.02050000..."
2,2,656,3,350656,1,0,828.83,701.91,407896.91458,4.518164e+06,...,North-west SL,17,NW Quad-International,155,NW Quad-International,3518,32,1,NonAttnmnt|35|WFRC,"{""x"": 407896.9145999998, ""y"": 4518164.2017, ""s..."
3,3,657,4,350657,1,0,531.35,531.28,409430.46088,4.518727e+06,...,North-west SL,17,NW Quad-International,155,NW Quad-International,3518,32,1,NonAttnmnt|35|WFRC,"{""x"": 409430.4609000003, ""y"": 4518726.88959999..."
4,4,2696,5,492696,1,0,575.28,574.81,435443.25244,4.435982e+06,...,Southwest,45,Payson-Salem,550,Payson-Salem,4907,43,2,NonAttnmnt|49|MAG,"{""x"": 435443.25239999965, ""y"": 4435981.8214, ""..."

In [15]:
#verify that shape exists and sdf was created correctly and get spatial reference
print(sdf_tazcentroids.iloc[0].SHAPE)

{'x': 409807.9715, 'y': 4551223.84, 'spatialReference': {'wkid': 26912, 'latestWkid': 26912}}

In [20]:
#spatial join tract centroid data to zip code data
sdf_tazcentroids_tract_join = sdf_tazcentroids.spatial.join(sdf_tract)

sdf_tazcentroids_tract_join.head()

,FID_left,TAZID,SORT,CO_TAZID,SUBAREAID,EXTERNAL,ACRES,DEVACRES,X,Y,...,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON
0,0,460,1,110460,1,0,322.29,322.29,409807.97148,4.551224e+06,...,125401,49011125401,1254.01,Census Tract 1254.01,G5020,S,38851207.0,98152968.0,+41.1344047,-112.1791968
1,1,461,2,110461,1,0,316.91,316.91,409818.05584,4.552025e+06,...,125401,49011125401,1254.01,Census Tract 1254.01,G5020,S,38851207.0,98152968.0,+41.1344047,-112.1791968
2,446,425,447,110425,1,0,803.72,672.64,405293.60212,4.553193e+06,...,125401,49011125401,1254.01,Census Tract 1254.01,G5020,S,38851207.0,98152968.0,+41.1344047,-112.1791968
3,447,427,448,110427,1,0,1142.45,1140.09,407425.18568,4.550026e+06,...,125401,49011125401,1254.01,Census Tract 1254.01,G5020,S,38851207.0,98152968.0,+41.1344047,-112.1791968
4,475,457,476,110457,1,0,322.31,322.31,408210.77535,4.552846e+06,...,125401,49011125401,1254.01,Census Tract 1254.01,G5020,S,38851207.0,98152968.0,+41.1344047,-112.1791968

In [22]:
df_tazcentroids_tract = sdf_tazcentroids_tract_join[['TAZID','GEOID']].copy()
df_tazcentroids_tract

      TAZID        GEOID
0       460  49011125401
1       461  49011125401
2       425  49011125401
3       427  49011125401
4       457  49011125401
...     ...          ...
2876    898  49035113511
2877   1422  49035113527
2878    940  49035113532
2879   1439  49035112907
2880   1440  49035112907

[2881 rows x 2 columns]

In [23]:
df_tazcentroids_tract.to_csv(os.path.join(results_folder, r"TAZ_CensusTract.csv"))